"""add saved_searches and search indexes

Revision ID: 00368f77ae5f
Revises: de2857f95da4
Create Date: 2026-03-27 01:38:16.273175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00368f77ae5f'
down_revision = 'de2857f95da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('query', sa.String(length=200), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('notify', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # GIN index for full-text search on listings (title + description)
    op.execute("""
        CREATE INDEX ix_listings_fts ON listings
        USING GIN (to_tsvector('spanish', coalesce(title, '') || ' ' || coalesce(description, '')))
    """)


def downgrade():
    op.execute("DROP INDEX IF EXISTS ix_listings_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_searches')
    # ### end Alembic commands ###
